# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Markdown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Markdown File
        run: |
          FILENAME=$(git diff --name-only HEAD^ HEAD | grep uploads/)
          echo "Detected new file: $FILENAME"

          # 파싱
          WEEK=$(echo $FILENAME | cut -d ']' -f 1 | tr -d '[')
          TYPE=$(echo $FILENAME | cut -d ']' -f 2 | tr -d '[' | awk '{print $2}')
          LEVEL=$(echo $FILENAME | cut -d ']' -f 3 | tr -d '[' | awk '{print $2}')
          PROB_NUM=$(echo $FILENAME | cut -d ' ' -f 4)
          PROB_NAME=$(echo $FILENAME | cut -d ' ' -f 5)

          # 날짜 계산 (GNU date 필요)
          START_DATE=$(date +"%Y-%m-%d")
          END_DATE=$(date -d "+7 days" +"%Y-%m-%d")

          # 마크다운 구문 생성
          MD_CONTENT="| ${WEEK} | ${START_DATE} <br> ~ ${END_DATE} | ${TYPE} | <p align=left> (https://www.acmicpc.net/problem/${PROB_NUM}) <br> 1️⃣ [${PROB_NAME}] </p> | <img height=\"20px\" width=\"25px\" src=\"https://static.solved.ac/tier_small/${LEVEL}.svg\"/> | - [ ] | - [ ] | - [ ] | - [ ] | - [ ] | - [ ] |"

          # 마크다운 파일에 추가
          echo "$MD_CONTENT" >> docs/시즌2_진행 및 내용.md

